version: "3.9"

services:
  studyapp_django:
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8002:8000"

  studyapp_celery_worker:
    env_file:
      - .env

  studyapp_celery_beat:
    env_file:
      - .env